webtalk_init -webtalk_dir C:/Users/User/Desktop/suli/MSc/Rendszerarchitect/shiftreg_tx/shiftreg_tx.sim/sim_1/behav/xsim/xsim.dir/shiftreg_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May  5 15:16:01 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1d0a1801-7d00-4253-88a5-9ef893d118cc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c8117c3ac49546d59270736ac3b2041b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "182" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "577 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5740_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3646703102 -regid "" -xml C:/Users/User/Desktop/suli/MSc/Rendszerarchitect/shiftreg_tx/shiftreg_tx.sim/sim_1/behav/xsim/xsim.dir/shiftreg_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/User/Desktop/suli/MSc/Rendszerarchitect/shiftreg_tx/shiftreg_tx.sim/sim_1/behav/xsim/xsim.dir/shiftreg_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/User/Desktop/suli/MSc/Rendszerarchitect/shiftreg_tx/shiftreg_tx.sim/sim_1/behav/xsim/xsim.dir/shiftreg_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
